Connect-AzureAD -TenantId 'tenantid'

$PasswordProfile = New-Object -TypeName Microsoft.Open.AzureAD.Model.PasswordProfile
$PasswordProfile.Password = "ChangeM3!"
New-AzureADUser -DisplayName "Lab1" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab1@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab1"
New-AzureADUser -DisplayName "Lab2" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab2@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab2"
New-AzureADUser -DisplayName "Lab3" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab3@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab3"
New-AzureADUser -DisplayName "Lab4" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab4@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab4"
New-AzureADUser -DisplayName "Lab5" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab5@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab5"
New-AzureADUser -DisplayName "Lab6" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab6@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab6"
New-AzureADUser -DisplayName "Lab7" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab7@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab7"
New-AzureADUser -DisplayName "Lab8" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab8@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab8"
New-AzureADUser -DisplayName "Lab9" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab9@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab9"
New-AzureADUser -DisplayName "Lab10" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab10@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab10"
New-AzureADUser -DisplayName "Lab11" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab11@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab11"
New-AzureADUser -DisplayName "Lab12" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab12@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab12"
New-AzureADUser -DisplayName "Lab13" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab13@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab13"
New-AzureADUser -DisplayName "Lab14" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab14@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab14"
New-AzureADUser -DisplayName "Lab15" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab15@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab15"
New-AzureADUser -DisplayName "Lab16" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab16@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab16"
New-AzureADUser -DisplayName "Lab17" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab17@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab17"
New-AzureADUser -DisplayName "Lab18" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab18@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab18"
New-AzureADUser -DisplayName "Lab19" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab19@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab19"
New-AzureADUser -DisplayName "Lab20" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab20@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab20"
New-AzureADUser -DisplayName "Lab21" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab21@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab21"
New-AzureADUser -DisplayName "Lab22" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab22@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab22"
New-AzureADUser -DisplayName "Lab23" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab23@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab23"
New-AzureADUser -DisplayName "Lab24" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab24@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab24"
New-AzureADUser -DisplayName "Lab25" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab25@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab25"
New-AzureADUser -DisplayName "Lab26" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab26@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab26"
New-AzureADUser -DisplayName "Lab27" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab27@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab27"
New-AzureADUser -DisplayName "Lab28" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab28@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab28"
New-AzureADUser -DisplayName "Lab29" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab29@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab29"
New-AzureADUser -DisplayName "Lab30" -PasswordProfile $PasswordProfile -UserPrincipalName "Lab30@vmwaresales101outlook.onmicrosoft.com" -AccountEnabled $true -MailNickName "Lab30"