az deployment sub create --name LevelUp-Lab1 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB1.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab2 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB2.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab3 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB3.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab4 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB4.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab4 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB4.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab5 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB5.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab6 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB6.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab7 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB7.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab8 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB8.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab9 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB9.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab10 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB10.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab11 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB11.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab12 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB12.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab13 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB13.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab14 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB14.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab15 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB15.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab16 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB16.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab17 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB17.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab18 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB18.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab19 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB19.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab20 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB20.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab21 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB21.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab22 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB22.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab23 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB23.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab24 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB24.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab25 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB25.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab26 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB26.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab27 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB27.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab28 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB28.parameters.json --no-wait
az deployment sub create --name LevelUp-Lab29 --location canadacentral --template-file ESLZDeploy.bicep --parameters LEVELUP-LAB29.parameters.json --no-wait

